formatting - Replaced tabs with spaces

diff --git a/overlay/opt/emcomm-tools/bin/et-audio b/overlay/opt/emcomm-tools/bin/et-audio
--- a/overlay/opt/emcomm-tools/bin/et-audio
+++ b/overlay/opt/emcomm-tools/bin/et-audio
@@ -54,17 +54,17 @@ update-config () {
        if [[ $? -eq 0 ]]; then
          et-log "Executing audio configuration script: ${AUDIO_INIT_SCRIPT}"
 
-	 CMD="${AUDIO_INIT_SCRIPT} ${AUDIO_CARD} ${AUDIO_DEVICE}"
-	 et-log "Running command: ${CMD}"
-	 ${CMD}
+         CMD="${AUDIO_INIT_SCRIPT} ${AUDIO_CARD} ${AUDIO_DEVICE}"
+         et-log "Running command: ${CMD}"
+         ${CMD}
 
-	 if [[ $? -ne 0 ]]; then
-	   et-log "Audio init script ${AUDIO_INIT_SCRIPT} failed. Can't start application."
-	   notify-user "Audio init script failed. Can't start application."
-	   exit 1
-	 fi
+         if [[ $? -ne 0 ]]; then
+           et-log "Audio init script ${AUDIO_INIT_SCRIPT} failed. Can't start application."
+           notify-user "Audio init script failed. Can't start application."
+           exit 1
+         fi
 	 
-	 exit 0
+         exit 0
        fi
 
        # Handle audio generically for most sound card interfaces
